INSERT INTO academic_information (school, department, programme) VALUES
('SoET', 'CSE', 'B.Tech in CSE'),
('SoET', 'CSE', 'B.Tech in CSE (Artificial Intelligence and Machine Learning)'),
('SoET', 'CSE', 'B.Tech in CSE (Bioscience)'),
('SoET', 'CSE', 'B.Tech in CSE (Computer Networking)'),
('SoET', 'CSE', 'B.Tech in CSE (Data Science and Machine Learning)'),
('SoET', 'CSE', 'B.Tech in CSE (Data Science)'),
('SoET', 'CSE', 'B.Tech in CSE (IOT & Cyber Security with Block Chain Technology)'),
('SoET', 'CSE', 'B.Tech in CSE (Software Engineering)'),
('SoET', 'CSE', 'B-Tech in CSE (AWS)'),
('SoET', 'CSE', 'B-Tech in CSE (AR/VR)'),
('SoET', 'CSE', 'PhD'),
('SoET', 'ECE', 'B.Tech in ECE'),
('SoET', 'ECE', 'B.Tech in ECE (Bio Medical)'),
('SoET', 'ECE', 'B.Tech in ECE (Industry Integrated)'),
('SoET', 'ECE', 'B.Tech in ECE (VLSI &Chip Design)'),
('SoET', 'ECE', 'PhD'),
('SoET', 'Mech', 'B.Tech in Mechanical Engineering'),
('SoET', 'Mech', 'B.Tech in Mechanical Engineering (Addictive Manufacturing)'),
('SoET', 'Mech', 'B.Tech in Mechanical Engineering (Automobile)'),
('SoET', 'Mech', 'PhD'),
('SoM', 'Management', 'BBA'),
('SoM', 'Management', 'MBA'),
('SoM', 'Management', 'PhD'),
('SoPAHS', 'Anaesthesia', 'B.Sc Anaesthesia & Operation Theatre Technology'),
('SoPAHS', 'Optometry', 'B.Sc Optometry'),
('SoPAHS', 'Radiology', 'B.Sc Radiology & Imaging Technology'),
('SoFS', 'Forensic', 'B.Sc Forensic Sciences'),
('SoFS', 'Forensic', 'M.Sc Forensic Sciences'),
('SoFS', 'Forensic', 'PhD'),
('CSoSAg', 'Agriculture', 'B.Sc.(Hons.) Agriculture');
