// YouTube API Service
import { fetchYouTubeData } from "@/services/apiService";

const API_KEY = "AIzaSyCTtWBJc0n1yVt1WInpcr7b7BKH-bBipQE";

// Enhanced cache with background refresh
const youtubeCache: { 
  videos: YouTubeVideo[] | null; 
  timestamp: number | null; 
  ttl: number;
  backgroundRefreshPromise: Promise<YouTubeVideo[]> | null;
} = {
  videos: null,
  timestamp: null,
  ttl: 5 * 60 * 1000, // 5 minutes cache
  backgroundRefreshPromise: null
};

// Separate caches for different content types
const contentCaches = {
  videos: { data: null as YouTubeVideo[] | null, timestamp: null as number | null },
  shorts: { data: null as YouTubeVideo[] | null, timestamp: null as number | null },
  posts: { data: null as YouTubeVideo[] | null, timestamp: null as number | null }
};

// YouTube channel
// Channel URL: https://www.youtube.com/channel/UCd6iyFcfC8mQxUP5Laltplg
const CHANNEL_ID = "UCd6iyFcfC8mQxUP5Laltplg";
// Channel uploads playlist ID (automatically generated by YouTube)
const PLAYLIST_ID = "UUd6iyFcfC8mQxUP5Laltplg";

interface YouTubeVideo {
  id: string;
  title: string;
  description: string;
  thumbnail: string;
  publishedAt: string;
  viewCount: string;
  likeCount?: string;
  favoriteCount?: string;
  duration?: string;
  contentType: 'video' | 'short' | 'post';
}

// YouTube API response interfaces
interface YouTubeSearchItem {
  id: {
    videoId: string;
  };
  snippet: {
    title: string;
    description: string;
    publishedAt: string;
    thumbnails: {
      medium: {
        url: string;
      };
      high: {
        url: string;
      };
    };
  };
  contentDetails?: {
    duration: string;
  };
}

interface YouTubePlaylistItem {
  contentDetails: {
    videoId: string;
  };
  snippet: {
    title: string;
    description: string;
    publishedAt: string;
    thumbnails: {
      medium: {
        url: string;
      };
      high: {
        url: string;
      };
    };
  };
}

interface YouTubeVideoStatistics {
  id: string;
  statistics: {
    viewCount: string;
    likeCount?: string;
    favoriteCount?: string;
  };
  contentDetails?: {
    duration: string;
  };
}

interface YouTubeSearchResponse {
  items: YouTubeSearchItem[];
}

interface YouTubePlaylistResponse {
  items: YouTubePlaylistItem[];
}

interface YouTubeStatisticsResponse {
  items: YouTubeVideoStatistics[];
}

// Function to determine content type based on video properties
const determineContentType = (title: string, description: string, duration?: string): 'video' | 'short' | 'post' => {
  // Convert to lowercase for easier matching
  const lowerTitle = title.toLowerCase();
  const lowerDescription = description.toLowerCase();

  // Log for debugging
  // console.log('Determining content type for:', { title: lowerTitle, description: lowerDescription, duration });

  // Check for shorts indicators - more aggressive detection
  if (lowerTitle.includes('#shorts') || 
      lowerTitle.includes('short') || 
      lowerTitle.includes('#short') ||
      lowerTitle.includes('ytshorts') ||
      lowerTitle.includes('reels') ||
      (duration && duration.startsWith('PT') && 
       ((duration.includes('S') && !duration.includes('M')) || 
        (duration.match(/PT(\d+)S/) && parseInt(duration.match(/PT(\d+)S/)![1]) <= 90)))) {
    return 'short';
  }

  // Check for post indicators (this is more heuristic-based)
  if (lowerTitle.includes('post') || 
      lowerDescription.includes('post') ||
      lowerTitle.includes('#post') ||
      lowerTitle.includes('community post') ||
      lowerTitle.includes('update') ||
      lowerTitle.includes('announcement') ||
      lowerTitle.includes('q&a') ||
      lowerTitle.includes('q & a')) {
    return 'post';
  }

  return 'video';
};

// Optimized function for fetching YouTube videos with background refresh
export const fetchYouTubeVideos = async (maxResults: number = 50, forceRefresh: boolean = false): Promise<YouTubeVideo[]> => {
  try {
    // Check if we have a background refresh in progress
    if (youtubeCache.backgroundRefreshPromise && !forceRefresh) {
      try {
        // Return the background refreshed data if available
        const backgroundData = await youtubeCache.backgroundRefreshPromise;
        return backgroundData;
      } catch (error) {
        console.warn("Background refresh failed, using cached data:", error);
        // Fall through to use cached data
      }
    }

    // Check cache first
    const now = Date.now();
    if (!forceRefresh && youtubeCache.videos && youtubeCache.timestamp && 
        (now - youtubeCache.timestamp) < youtubeCache.ttl) {
      // Start background refresh if cache is older than 2 minutes
      if ((now - youtubeCache.timestamp) > 2 * 60 * 1000 && !youtubeCache.backgroundRefreshPromise) {
        youtubeCache.backgroundRefreshPromise = fetchYouTubeVideos(maxResults, true)
          .then(data => {
            youtubeCache.backgroundRefreshPromise = null;
            return data;
          })
          .catch(error => {
            youtubeCache.backgroundRefreshPromise = null;
            throw error;
          });
      }

      return youtubeCache.videos;
    }

    // Validate API key
    if (!API_KEY) {
      console.warn("No API key provided. Please set your YouTube API key.");
    }

    // Validate channel ID
    if (!CHANNEL_ID) {
      throw new Error("Channel ID is not defined. Please set your YouTube channel ID.");
    }

    // First, try to fetch from a specific playlist if PLAYLIST_ID is defined
    if (PLAYLIST_ID) {
      // Fetch playlist items with content details
      const playlistData = await fetchYouTubeData('playlistItems', {
        key: API_KEY,
        playlistId: PLAYLIST_ID,
        part: 'snippet,id,contentDetails',
        maxResults: maxResults.toString()
      }) as YouTubePlaylistResponse;

      // Handle case where proxy returns generic success message instead of YouTube data
      if (playlistData && typeof playlistData === 'object' && 'status' in playlistData && playlistData.status === 'success' && 
          'message' in playlistData && playlistData.message === 'Operation completed') {
        console.warn('Proxy returned generic success message instead of YouTube data. Falling back to direct API call.');
        // Try direct API call as fallback
        return await fetchYouTubeVideosDirect(maxResults, 'playlist');
      }

      // Validate response structure
      if (!playlistData || !playlistData.items || !Array.isArray(playlistData.items)) {
        console.warn('Invalid playlist response structure from YouTube API. Falling back to direct API call.');
        // Try direct API call as fallback
        return await fetchYouTubeVideosDirect(maxResults, 'playlist');
      }

      // Get video IDs to fetch statistics and content details
      const videoIds = playlistData.items.map((item: YouTubePlaylistItem) => item.contentDetails.videoId).join(',');

      const statsDataResult = await fetchYouTubeData('videos', {
        key: API_KEY,
        id: videoIds,
        part: 'statistics,contentDetails'
      }) as YouTubeStatisticsResponse;

      // Handle case where proxy returns generic success message instead of YouTube data
      if (statsDataResult && typeof statsDataResult === 'object' && 'status' in statsDataResult && statsDataResult.status === 'success' && 
          'message' in statsDataResult && statsDataResult.message === 'Operation completed') {
        console.warn('Proxy returned generic success message for statistics. Falling back to direct API call.');
        // Try direct API call as fallback
        return await fetchYouTubeVideosDirect(maxResults, 'playlist');
      }

      // Validate statistics response structure
      if (!statsDataResult || !statsDataResult.items || !Array.isArray(statsDataResult.items)) {
        console.warn('Invalid statistics response structure from YouTube API. Falling back to direct API call.');
        // Try direct API call as fallback
        return await fetchYouTubeVideosDirect(maxResults, 'playlist');
      }

      // Create a map of video IDs to statistics and content details
      const statsMap: Record<string, YouTubeVideoStatistics | undefined> = {};
      statsDataResult.items.forEach((item: YouTubeVideoStatistics) => {
        statsMap[item.id] = item;
      });

      // Process the data to match our YouTubeVideo interface
      const videos: YouTubeVideo[] = playlistData.items.map((item: YouTubePlaylistItem) => {
        const stats = statsMap[item.contentDetails.videoId];
        const viewCount = stats?.statistics?.viewCount || "N/A";
        const likeCount = stats?.statistics?.likeCount || "0";
        const favoriteCount = stats?.statistics?.favoriteCount || "0";
        const duration = stats?.contentDetails?.duration;
        
        // Determine content type based on available data
        const contentType = determineContentType(
          item.snippet.title, 
          item.snippet.description, 
          duration
        );
        
        return {
          id: item.contentDetails.videoId,
          title: item.snippet.title,
          description: item.snippet.description,
          thumbnail: item.snippet.thumbnails.medium?.url || item.snippet.thumbnails.high?.url || "",
          publishedAt: item.snippet.publishedAt,
          viewCount,
          likeCount,
          favoriteCount,
          duration,
          contentType
        };
      });

      // Cache the results
      youtubeCache.videos = videos;
      youtubeCache.timestamp = Date.now();

      return videos;
    }

    // Fetch search results
    const searchData = await fetchYouTubeData('search', {
      key: API_KEY,
      channelId: CHANNEL_ID,
      part: 'snippet,id',
      order: 'date',
      maxResults: maxResults.toString(),
      type: 'video'
    }) as YouTubeSearchResponse;

    // Handle case where proxy returns generic success message instead of YouTube data
    if (searchData && typeof searchData === 'object' && 'status' in searchData && searchData.status === 'success' && 
        'message' in searchData && searchData.message === 'Operation completed') {
      console.warn('Proxy returned generic success message instead of YouTube data. Falling back to direct API call.');
      // Try direct API call as fallback
      return await fetchYouTubeVideosDirect(maxResults, 'channel');
    }

    // Validate response structure
    if (!searchData || !searchData.items || !Array.isArray(searchData.items)) {
      console.warn('Invalid search response structure from YouTube API. Falling back to direct API call.');
      // Try direct API call as fallback
      return await fetchYouTubeVideosDirect(maxResults, 'channel');
    }

    // Get video IDs to fetch statistics and content details
    const videoIds = searchData.items.map((item: YouTubeSearchItem) => item.id.videoId).join(',');

    const statsDataResult = await fetchYouTubeData('videos', {
      key: API_KEY,
      id: videoIds,
      part: 'statistics,contentDetails'
    }) as YouTubeStatisticsResponse;

    // Handle case where proxy returns generic success message instead of YouTube data
    if (statsDataResult && typeof statsDataResult === 'object' && 'status' in statsDataResult && statsDataResult.status === 'success' && 
        'message' in statsDataResult && statsDataResult.message === 'Operation completed') {
      console.warn('Proxy returned generic success message for statistics. Falling back to direct API call.');
      // Try direct API call as fallback
      return await fetchYouTubeVideosDirect(maxResults, 'channel');
    }

    // Validate statistics response structure
    if (!statsDataResult || !statsDataResult.items || !Array.isArray(statsDataResult.items)) {
      console.warn('Invalid statistics response structure from YouTube API. Falling back to direct API call.');
      // Try direct API call as fallback
      return await fetchYouTubeVideosDirect(maxResults, 'channel');
    }

    // Create a map of video IDs to statistics and content details
    const statsMap: Record<string, YouTubeVideoStatistics | undefined> = {};
    statsDataResult.items.forEach((item: YouTubeVideoStatistics) => {
      statsMap[item.id] = item;
    });

    // Process the data to match our YouTubeVideo interface
    const videos: YouTubeVideo[] = searchData.items.map((item: YouTubeSearchItem) => {
      const stats = statsMap[item.id.videoId];
      const viewCount = stats?.statistics?.viewCount || "N/A";
      const likeCount = stats?.statistics?.likeCount || "0";
      const favoriteCount = stats?.statistics?.favoriteCount || "0";
      const duration = stats?.contentDetails?.duration;
      
      // Determine content type based on available data
      const contentType = determineContentType(
        item.snippet.title, 
        item.snippet.description, 
        duration
      );
      
      return {
        id: item.id.videoId,
        title: item.snippet.title,
        description: item.snippet.description,
        thumbnail: item.snippet.thumbnails.medium?.url || item.snippet.thumbnails.high?.url || "",
        publishedAt: item.snippet.publishedAt,
        viewCount,
        likeCount,
        favoriteCount,
        duration,
        contentType
      };
    });

    // Cache the results
    youtubeCache.videos = videos;
    youtubeCache.timestamp = Date.now();

    return videos;
  } catch (error) {
    console.error("Error fetching YouTube videos:", error);
    
    // If we have cached data, return it even if fetch failed
    if (youtubeCache.videos) {
      return youtubeCache.videos;
    }
    
    // Handle quota exceeded error specifically
    if (error instanceof Error && error.message.includes('quota')) {
      throw new Error("YouTube API quota exceeded. Please try again later.");
    }
    
    if (error instanceof Error) {
      throw new Error(`Failed to fetch videos from YouTube: ${error.message}`);
    } else {
      throw new Error("Failed to fetch videos from YouTube: Unknown error");
    }
  }
};

// Function to fetch content by type - simplified version that fetches all and filters
export const fetchYouTubeContentByType = async (contentType: 'videos' | 'shorts' | 'posts', maxResults: number = 50): Promise<YouTubeVideo[]> => {
  try {
    const now = Date.now();
    const cache = contentCaches[contentType];

    // Check cache first
    if (cache.data && cache.timestamp && (now - cache.timestamp) < youtubeCache.ttl) {
      return cache.data;
    }

    // Fetch all videos (this ensures we get content from all types)
    const allVideos = await fetchYouTubeVideos(maxResults * 3); // Fetch more to ensure we have enough of each type

    // Filter by content type
    const filteredVideos = allVideos.filter(video => {
      // Special handling for 'videos' - it should include both 'video' and any that don't match shorts/posts
      if (contentType === 'videos') {
        return video.contentType === 'video';
      } else if (contentType === 'shorts') {
        return video.contentType === 'short';
      } else if (contentType === 'posts') {
        return video.contentType === 'post';
      }
      return false;
    }).slice(0, maxResults);

    // If we don't have enough content for a specific type, show all content in that tab
    if (filteredVideos.length === 0 && allVideos.length > 0) {
      const fallbackVideos = allVideos.slice(0, maxResults);
      // Update cache
      cache.data = fallbackVideos;
      cache.timestamp = now;
      return fallbackVideos;
    }

    // Update cache
    cache.data = filteredVideos;
    cache.timestamp = now;

    return filteredVideos;
  } catch (error) {
    console.error(`Error fetching ${contentType}:`, error);
    // Return empty array on error so the UI can handle it gracefully
    return [];
  }
};

// Fallback function for direct API calls when proxy fails
const fetchYouTubeVideosDirect = async (maxResults: number = 50, mode: 'playlist' | 'channel' = 'channel'): Promise<YouTubeVideo[]> => {
  try {
    if (mode === 'playlist' && PLAYLIST_ID) {
      // Fetch from playlist directly
      const playlistUrl = `https://www.googleapis.com/youtube/v3/playlistItems?key=${API_KEY}&playlistId=${PLAYLIST_ID}&part=snippet,id,contentDetails&maxResults=${maxResults}`;

      const playlistResponse = await fetch(playlistUrl);
      if (!playlistResponse.ok) {
        throw new Error(`Playlist API error: ${playlistResponse.status} - ${await playlistResponse.text()}`);
      }

      const playlistData = await playlistResponse.json();

      // Validate response structure
      if (!playlistData || !playlistData.items || !Array.isArray(playlistData.items)) {
        throw new Error('Invalid playlist response structure from YouTube API');
      }

      // Get video IDs to fetch statistics
      const videoIds = playlistData.items.map((item: YouTubePlaylistItem) => item.contentDetails.videoId).join(',');

      // Fetch video statistics with like and favorite counts and content details
      const statsUrl = `https://www.googleapis.com/youtube/v3/videos?key=${API_KEY}&id=${videoIds}&part=statistics,contentDetails`;

      const statsResponse = await fetch(statsUrl);
      if (!statsResponse.ok) {
        throw new Error(`Statistics API error: ${statsResponse.status} - ${await statsResponse.text()}`);
      }

      const statsData = await statsResponse.json();

      // Validate statistics response structure
      if (!statsData || !statsData.items || !Array.isArray(statsData.items)) {
        throw new Error('Invalid statistics response structure from YouTube API');
      }

      // Create a map of video IDs to statistics and content details
      const statsMap: Record<string, YouTubeVideoStatistics | undefined> = {};
      statsData.items.forEach((item: YouTubeVideoStatistics) => {
        statsMap[item.id] = item;
      });

      // Process the data to match our YouTubeVideo interface
      const videos: YouTubeVideo[] = playlistData.items.map((item: YouTubePlaylistItem) => {
        const stats = statsMap[item.contentDetails.videoId];
        const viewCount = stats?.statistics?.viewCount || "N/A";
        const likeCount = stats?.statistics?.likeCount || "0";
        const favoriteCount = stats?.statistics?.favoriteCount || "0";
        const duration = stats?.contentDetails?.duration;
        
        // Determine content type based on available data
        const contentType = determineContentType(
          item.snippet.title, 
          item.snippet.description, 
          duration
        );
        
        return {
          id: item.contentDetails.videoId,
          title: item.snippet.title,
          description: item.snippet.description,
          thumbnail: item.snippet.thumbnails.medium?.url || item.snippet.thumbnails.high?.url || "",
          publishedAt: item.snippet.publishedAt,
          viewCount,
          likeCount,
          favoriteCount,
          duration,
          contentType
        };
      });

      // Cache the results
      youtubeCache.videos = videos;
      youtubeCache.timestamp = Date.now();

      return videos;
    } else {
      // Fetch from channel directly
      const searchUrl = `https://www.googleapis.com/youtube/v3/search?key=${API_KEY}&channelId=${CHANNEL_ID}&part=snippet,id&order=date&maxResults=${maxResults}&type=video`;

      const searchResponse = await fetch(searchUrl);
      if (!searchResponse.ok) {
        throw new Error(`Search API error: ${searchResponse.status} - ${await searchResponse.text()}`);
      }

      const searchData = await searchResponse.json();

      // Validate response structure
      if (!searchData || !searchData.items || !Array.isArray(searchData.items)) {
        throw new Error('Invalid search response structure from YouTube API');
      }

      // Get video IDs to fetch statistics
      const videoIds = searchData.items.map((item: YouTubeSearchItem) => item.id.videoId).join(',');

      // Fetch video statistics with like and favorite counts and content details
      const statsUrl = `https://www.googleapis.com/youtube/v3/videos?key=${API_KEY}&id=${videoIds}&part=statistics,contentDetails`;

      const statsResponse = await fetch(statsUrl);
      if (!statsResponse.ok) {
        throw new Error(`Statistics API error: ${statsResponse.status} - ${await statsResponse.text()}`);
      }

      const statsData = await statsResponse.json();

      // Validate statistics response structure
      if (!statsData || !statsData.items || !Array.isArray(statsData.items)) {
        throw new Error('Invalid statistics response structure from YouTube API');
      }

      // Create a map of video IDs to statistics and content details
      const statsMap: Record<string, YouTubeVideoStatistics | undefined> = {};
      statsData.items.forEach((item: YouTubeVideoStatistics) => {
        statsMap[item.id] = item;
      });

      // Process the data to match our YouTubeVideo interface
      const videos: YouTubeVideo[] = searchData.items.map((item: YouTubeSearchItem) => {
        const stats = statsMap[item.id.videoId];
        const viewCount = stats?.statistics?.viewCount || "N/A";
        const likeCount = stats?.statistics?.likeCount || "0";
        const favoriteCount = stats?.statistics?.favoriteCount || "0";
        const duration = stats?.contentDetails?.duration;
        
        // Determine content type based on available data
        const contentType = determineContentType(
          item.snippet.title, 
          item.snippet.description, 
          duration
        );
        
        return {
          id: item.id.videoId,
          title: item.snippet.title,
          description: item.snippet.description,
          thumbnail: item.snippet.thumbnails.medium?.url || item.snippet.thumbnails.high?.url || "",
          publishedAt: item.snippet.publishedAt,
          viewCount,
          likeCount,
          favoriteCount,
          duration,
          contentType
        };
      });

      // Cache the results
      youtubeCache.videos = videos;
      youtubeCache.timestamp = Date.now();

      return videos;
    }
  } catch (error) {
    console.error("Error in direct YouTube API call:", error);
    throw error;
  }
};

// Clear cache
export const clearYouTubeCache = (): void => {
  youtubeCache.videos = null;
  youtubeCache.timestamp = null;
  youtubeCache.backgroundRefreshPromise = null;
  
  // Clear content type caches
  contentCaches.videos.data = null;
  contentCaches.videos.timestamp = null;
  contentCaches.shorts.data = null;
  contentCaches.shorts.timestamp = null;
  contentCaches.posts.data = null;
  contentCaches.posts.timestamp = null;
};

// Fetch a single video by ID (for detailed view)
export const fetchYouTubeVideo = async (videoId: string): Promise<YouTubeVideo | null> => {
  try {
    // First check if the video is in our cached list
    if (youtubeCache.videos) {
      const cachedVideo = youtubeCache.videos.find(v => v.id === videoId);
      if (cachedVideo) {
        return cachedVideo;
      }
    }
    
    // If not in cache, fetch from API
    const response = await fetch(
      `https://www.googleapis.com/youtube/v3/videos?key=${API_KEY}&id=${videoId}&part=snippet,statistics,contentDetails`
    );
    
    if (!response.ok) {
      throw new Error(`YouTube API error: ${response.statusText}`);
    }
    
    const data = await response.json();
    
    if (data.items.length === 0) {
      return null;
    }
    
    const item = data.items[0];
    const contentType = determineContentType(
      item.snippet.title, 
      item.snippet.description, 
      item.contentDetails?.duration
    );
    
    return {
      id: item.id,
      title: item.snippet.title,
      description: item.snippet.description,
      thumbnail: item.snippet.thumbnails.medium?.url || item.snippet.thumbnails.high?.url || "",
      publishedAt: item.snippet.publishedAt,
      viewCount: item.statistics?.viewCount || "N/A",
      likeCount: item.statistics?.likeCount || "0",
      favoriteCount: item.statistics?.favoriteCount || "0",
      duration: item.contentDetails?.duration,
      contentType
    };
  } catch (error) {
    console.error("Error fetching YouTube video:", error);
    return null;
  }
};