"use client";

import { useState, useEffect } from "react";

// UI Components
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogClose } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "@/components/ui/use-toast";

// Icons
import { Edit, Save, Search, Loader2 } from "lucide-react";
import { useRouter } from "next/navigation";

// Local Components
import { useAdminData } from "@/components/AdminLayout";
import FilterSection from "./FilterSection";
import RobustImage from "./RobustImage";
import CustomDatePicker from "./CustomDatePicker";

// Services and Types
import { Student, updateStudentData, fetchStudentsData, getDirectImageUrl, fetchAcademicInfo, AcademicInfo } from "@/services/apiService";
import { UserRole } from "@/contexts/auth-context";
import { useAuth } from "@/contexts/useAuth";

// Date utilities
import { formatDateForDisplay, formatDateForSubmission } from "@/lib/dateUtils";
import { YEARS } from "@/lib/constants";

interface AlumniManagementTabProps {
  students: Student[];
  onStudentUpdate: (student: Student) => void;
  userRole?: UserRole;
  currentStudent?: Student | null;
}

const AlumniManagementTab = (props: AlumniManagementTabProps) => {
  const router = useRouter();
  const adminData = useAdminData();
  const { refreshData } = useAuth();
  const isAdmin = props.userRole === "admin" || props.userRole === "alumni-manager";
  const students = props.students ?? (isAdmin ? adminData.students : []);
  const onStudentUpdate = props.onStudentUpdate ?? (isAdmin ? (updatedStudent: Student) => adminData.setStudents(prev => prev.map(s => s.id === updatedStudent.id ? updatedStudent : s)) : undefined);
  const [editingStudent, setEditingStudent] = useState<string | null>(null);
  const [editedData, setEditedData] = useState<Partial<Student>>({});
  const [searchTerm, setSearchTerm] = useState("");
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  const [selectedYear, setSelectedYear] = useState("all");
  const [selectedSchool, setSelectedSchool] = useState("all");
  const [selectedProgramme, setSelectedProgramme] = useState("all");
  const [selectedDepartment, setSelectedDepartment] = useState("all");

  const [academicData, setAcademicData] = useState<AcademicInfo[]>([]);

  useEffect(() => {
    const loadAcademicData = async () => {
      try {
        const data = await fetchAcademicInfo();
        setAcademicData(data);
      } catch (error) {
        console.error("Failed to fetch academic data", error);
      }
    };
    loadAcademicData();
  }, []);

  const uniqueSchools = Array.from(new Set(academicData.map(a => a.school)));
  const uniqueDepartments = editedData.school ? Array.from(new Set(academicData.filter(a => a.school === editedData.school).map(a => a.department))) : [];
  const uniqueProgrammes = editedData.department ? Array.from(new Set(academicData.filter(a => a.school === editedData.school && a.department === editedData.department).map(a => a.programme))) : [];


  const handleEditStudent = (studentId: string) => {

    const student = students.find(s => s.id === studentId);
    if (student) {
      // Check permissions
      if (props.userRole === "student" && props.currentStudent && student.registrationNo !== props.currentStudent.registrationNo) {
        toast({
          title: "Access Denied",
          description: "You can only edit your own profile.",
          variant: "destructive",
        });
        return;
      }
      
      setEditingStudent(studentId);
      setEditedData(student);
    }
  };

  const handleEmailClick = (student: Student) => {
    if (!student.email) return;
    const subject = 'Hello from CUTMAP Alumni Network';
    const body = `Hi ${student.name},

I hope this email finds you well. I wanted to reach out regarding the CUTMAP Alumni Network.

Best regards,
[Your Name]

Generated by CUTMAP Alumni Portal`;
    const mailtoUrl = `mailto:${student.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    setTimeout(() => {
      window.location.href = mailtoUrl;
    }, 100);
  };

  const handleSaveStudent = async () => {
    try {
      setSaving(true);
      setShowSuccess(false);
      if (!editedData || !editedData.registrationNo) {
        toast({
          title: "Error",
          description: "Missing student registration number.",
          variant: "destructive",
        });
        setSaving(false);
        return;
      }
      toast({
        title: "Saving changes...",
        description: "Please wait while we update the alumni details.",
      });
      // Construct a full payload with all required Student fields
      const fullPayload: Student = {
        id: editedData.id || "",
        registrationNo: editedData.registrationNo || "",
        name: editedData.name || "",
        email: editedData.email || "",
        phone: editedData.phone || "",
        school: editedData.school || "",
        programme: editedData.programme || "",
        graduationYear: editedData.graduationYear || "",
        designation: editedData.designation || "",
        currentPosition: editedData.currentPosition || "",
        currentDesignation: editedData.currentDesignation || editedData.designation || "",
        organisation: editedData.organisation || "",
        placeOfWork: editedData.placeOfWork || "",
        areaOfInterest: editedData.areaOfInterest || "",
        location: editedData.location || "",
        universityName: editedData.universityName || "",
        areaOfStudy: editedData.areaOfStudy || "",
        dob: formatDateForSubmission(editedData.dob || ""),
        linkedinId: editedData.linkedinId || "",
        photoUrl: editedData.photoUrl || "",
        address: editedData.address || "",
        feedback: editedData.feedback || "",
        department: editedData.department || "",
        skills: Array.isArray(editedData.skills) ? editedData.skills : (editedData.skills ? [editedData.skills] : []),
        Timestamp: editedData.Timestamp || new Date().toISOString(),
        currentJob: editedData.currentPosition || "",
        currentjob: editedData.currentPosition || ""
      };
      // Map department and school roles to admin for API call
      const apiUserRole = (props.userRole === "department" || props.userRole === "school") ? "admin" : (props.userRole || "student");
      await updateStudentData(fullPayload, apiUserRole as "student" | "admin");
      // Force a global re-fetch to ensure all components and caches have the latest data
      if (refreshData) {
        await refreshData(true);
      }
      setShowSuccess(true);
      setTimeout(() => {
        setShowSuccess(false);
        setEditingStudent(null);
        setEditedData({});
      }, 1500); // Show success for 1.5s, then close
      setSuccessMessage("Alumni data updated successfully!");
      if (onStudentUpdate) {
        onStudentUpdate(fullPayload);
      }
      setTimeout(() => setSuccessMessage(null), 3000);
      toast({
        title: "Alumni updated!",
        description: "The changes have been saved and are now visible.",
      });
    } catch (error) {
      const errMsg = error instanceof Error ? error.message : "Failed to update alumni data.";
      toast({
        title: "Error",
        description: errMsg,
        variant: "destructive",
      });
    } finally {
      setSaving(false);
    }
  };

  const handleCancelEdit = () => {
    setEditingStudent(null);
    setEditedData({});
  };

  // Sort students: Job/Higher study students first, then "NA" students at bottom, finally by Timestamp
  const sortedStudents = [...students].sort((a, b) => {
    // Helper function to check if student has complete job information
    const hasCompleteJobInfo = (student: Student) => {
      const hasOrganisation = student.organisation && 
        student.organisation !== "Not specified" && 
        student.organisation !== "NA" &&
        student.organisation.trim() !== "";
      
      const hasPosition = (student.currentPosition && 
        student.currentPosition !== "Not specified" && 
        student.currentPosition !== "NA" &&
        student.currentPosition.trim() !== "") ||
        (student.designation && 
        student.designation !== "Not specified" && 
        student.designation !== "NA" &&
        student.designation.trim() !== "");
      
      return hasOrganisation && hasPosition;
    };

    // Helper function to check if student has complete higher studies information
    const hasCompleteStudiesInfo = (student: Student) => {
      return (student.areaOfStudy && 
        student.areaOfStudy !== "Not specified" && 
        student.areaOfStudy !== "NA") &&
        (student.universityName &&
        student.universityName !== "Not specified" &&
        student.universityName !== "NA");
    };

    // Check completion status for both students
    const aHasJob = hasCompleteJobInfo(a);
    const aHasStudies = hasCompleteStudiesInfo(a);
    const aIsComplete = aHasJob || aHasStudies;

    const bHasJob = hasCompleteJobInfo(b);
    const bHasStudies = hasCompleteStudiesInfo(b);
    const bIsComplete = bHasJob || bHasStudies;

    // Primary sort: Complete info (job or studies) vs incomplete
    if (aIsComplete && !bIsComplete) return -1;
    if (!aIsComplete && bIsComplete) return 1;

    // Secondary sort: Within same completion status, prioritize job over studies
    if (aIsComplete && bIsComplete) {
      if (aHasJob && !bHasJob) return -1;
      if (!aHasJob && bHasJob) return 1;
    }

    // Tertiary sort: Timestamp (latest first)
    const dateA = a.Timestamp ? new Date(a.Timestamp) : new Date(0);
    const dateB = b.Timestamp ? new Date(b.Timestamp) : new Date(0);
    return dateB.getTime() - dateA.getTime();
  });

  // Filter students - only show approved students by default
  const filteredStudents = sortedStudents.filter(student => {
    // First check approval status
    const isApproved = student.Status === 'Approved';
    if (!isApproved) return false;
    
    // Apply year filter - check if the year includes the selected year
    if (selectedYear !== 'all' && student.graduationYear && 
        !student.graduationYear.toString().includes(selectedYear)) {
      return false;
    }
    
    // Apply school filter - case-insensitive partial match
    if (selectedSchool !== 'all' && student.school && 
        !student.school.toLowerCase().includes(selectedSchool.toLowerCase())) {
      return false;
    }
    
    // Apply programme filter - case-insensitive partial match
    if (selectedProgramme !== 'all' && student.programme && 
        !student.programme.toLowerCase().includes(selectedProgramme.toLowerCase())) {
      return false;
    }
    
    // Apply department filter
    if (selectedDepartment !== 'all' && student.department && 
        !student.department.toLowerCase().includes(selectedDepartment.toLowerCase())) {
      return false;
    }
    
    // Apply search term filter if provided
    if (searchTerm) {
      const search = searchTerm.toLowerCase();
      const matchesSearch = 
        (student.registrationNo && typeof student.registrationNo === 'string' && student.registrationNo.toLowerCase().includes(search)) ||
        (student.name && typeof student.name === 'string' && student.name.toLowerCase().includes(search)) ||
        (student.email && typeof student.email === 'string' && student.email.toLowerCase().includes(search)) ||
        (student.school && typeof student.school === 'string' && student.school.toLowerCase().includes(search)) ||
        (student.department && typeof student.department === 'string' && student.department.toLowerCase().includes(search)) ||
        (student.programme && typeof student.programme === 'string' && student.programme.toLowerCase().includes(search)) ||
        (student.currentPosition && typeof student.currentPosition === 'string' && student.currentPosition.toLowerCase().includes(search)) ||
        (student.organisation && typeof student.organisation === 'string' && student.organisation.toLowerCase().includes(search));
      
      if (!matchesSearch) return false;
    }
    
    return true;
  });
  


  return (
    <Card>
      {successMessage && (
        <div className="mb-4 p-3 rounded-lg text-green-900 bg-green-100 border border-green-300 text-center font-semibold">
          {successMessage}
        </div>
      )}
      <CardHeader>
        {/* Remove the CardTitle and Label for a cleaner UI */}
        <div></div>
      </CardHeader>
      <CardContent>
        {/* Sticky and horizontally scrollable FilterSection Bar on mobile */}
        <div className="sticky top-0 z-40 bg-white/90 backdrop-blur-md shadow rounded-b-none rounded-t-lg px-0 py-0 mb-4 w-full overflow-x-auto whitespace-nowrap">
          <FilterSection
            students={students}
            filteredStudents={filteredStudents}
            selectedYear={selectedYear}
            selectedSchool={selectedSchool}
            selectedProgramme={selectedProgramme}
            selectedDepartment={selectedDepartment}
            searchTerm={searchTerm}
            onYearChange={setSelectedYear}
            onSchoolChange={setSelectedSchool}
            onProgrammeChange={setSelectedProgramme}
            onDepartmentChange={setSelectedDepartment}
            onSearchChange={setSearchTerm}
            onClearFilters={() => {
              setSearchTerm("");
              setSelectedSchool("all");
              setSelectedYear("all");
              setSelectedProgramme("all");
              setSelectedDepartment("all");
            }}
          />
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredStudents.map((student, index) => (
            <div
              key={`${student.id}-${index}`}
              onClick={() => router.push(`/alumni-directory/detail?id=${student.registrationNo}`)}
              className={`border rounded-lg p-4 relative cursor-pointer hover:shadow-lg transition-shadow ${
                index % 2 === 0
                  ? 'bg-gradient-to-br from-pink-100 via-blue-100 to-violet-100'
                  : 'bg-gradient-to-br from-yellow-100 via-green-100 to-sky-100'
              }`}
            >
              {/* Edit button at top right - show for all management roles except cadmin */}
              {(props.userRole === "admin" || props.userRole === "alumni-manager" || props.userRole === "department" || props.userRole === "school") && (
                <Button size="sm" variant="outline" onClick={(e) => { e.stopPropagation(); handleEditStudent(student.id); }} className="absolute top-2 right-2 z-10">
                  <Edit className="h-4 w-4 mr-1" />
                  Edit
                </Button>
              )}
              <div className="flex items-center space-x-4 mb-4">
                <RobustImage 
                  photoUrl={student.photoUrl}
                  studentName={student.name}
                  size="md"
                />
                <div>
                  <h3 className="font-semibold text-lg">{student.name}</h3>
                  <p className="text-gray-600">{student.programme}</p>
                  <p className="text-gray-500 text-sm">Reg. No: <span className="font-medium">{student.registrationNo || '-'}</span></p>
                  <p className="text-gray-500 text-sm">Graduation Year: <span className="font-medium">{student.graduationYear || '-'}</span></p>
                </div>
              </div>
              
              {/* Contact Buttons */}
              <div className="flex justify-center gap-2 mt-2 mb-3">
                {student.linkedinId && student.linkedinId !== "NA" && student.linkedinId !== "Not specified" && (
                  <a 
                    href={student.linkedinId.startsWith('http') ? student.linkedinId : `https://linkedin.com/in/${student.linkedinId}`} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-blue-500 bg-blue-500 text-white hover:bg-blue-600 hover:border-blue-600 hover:shadow-lg h-8 w-8"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/>
                    </svg>
                  </a>
                )}
                {student.phone && student.phone !== "NA" && student.phone !== "Not specified" && (
                  <>
                    {/* Mobile view - show icon only */}
                    <a 
                      href={`tel:${student.phone}`} 
                      className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-green-500 bg-green-500 text-white hover:bg-green-600 hover:border-green-600 hover:shadow-lg h-8 w-8 sm:hidden"
                    >
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path>
                      </svg>
                    </a>
                    {/* Desktop view - show phone number with calling icon */}
                    <a 
                      href={`tel:${student.phone}`} 
                      className="hidden sm:inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-green-500 bg-green-500 text-white hover:bg-green-600 hover:border-green-600 hover:shadow-lg h-8 px-3 gap-2"
                    >
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-white">
                        <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path>
                      </svg>
                      {student.phone}
                    </a>
                  </>
                )}
                {student.email && student.email !== "NA" && student.email !== "Not specified" && (
                  <a 
                    href={`mailto:${student.email}`} 
                    className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-red-500 bg-red-500 text-white hover:bg-red-600 hover:border-red-600 hover:shadow-lg h-8 w-8"
                    onClick={(e) => {
                      e.preventDefault();
                      handleEmailClick(student);
                    }}
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
                      <polyline points="22,6 12,13 2,6"></polyline>
                    </svg>
                  </a>
                )}
              </div>
            </div>
          ))}
          
          {filteredStudents.length === 0 && searchTerm && (
            <div className="text-center py-8 text-gray-500">
              <Search className="h-12 w-12 mx-auto mb-4" />
              <p>No alumni found matching "{searchTerm}"</p>
            </div>
          )}
        </div>
        {/* Edit Modal - Only shown for management roles except cadmin */}
        <Dialog open={!!editingStudent && props.userRole !== "student" && props.userRole !== "cadmin"} onOpenChange={open => { if (!open) handleCancelEdit(); }}>
          <DialogContent className="max-w-3xl w-full max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Edit Alumni</DialogTitle>
              <DialogDescription>Update alumni details and save changes.</DialogDescription>
            </DialogHeader>
            <div className="space-y-4">
              <div className="flex items-center space-x-4 mb-4">
                <RobustImage 
                  photoUrl={editedData.photoUrl || ''}
                  studentName={editedData.name || ''}
                  size="md"
                />
                <div>
                  <h3 className="font-semibold text-lg">{editedData.name}</h3>
                  <p className="text-gray-600">{editedData.programme}</p>
                </div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {/* Admin fields */}
                {(props.userRole === "admin" || props.userRole === "alumni-manager" || props.userRole === "cadmin") && ([...Array(20)].map((_, i) => {
                  const fields = [
                    { label: "Name", key: "name", editable: true, readonly: false },
                    { label: "Email", key: "email", editable: true, readonly: false },
                    { label: "Personal Email", key: "personalEmail", editable: true, readonly: false },
                    { label: "Phone", key: "phone", editable: true, readonly: false },
                    { label: "School", key: "school", editable: true, readonly: false, type: "select", options: uniqueSchools,
                      onChange: (val: string) => setEditedData(prev => ({ ...prev, school: val, department: "", programme: "" }))
                    },
                    { label: "Department", key: "department", editable: true, readonly: false, type: "select", options: uniqueDepartments,
                      onChange: (val: string) => setEditedData(prev => ({ ...prev, department: val, programme: "" }))
                    },
                    { label: "Programme", key: "programme", editable: true, readonly: false, type: "select", options: uniqueProgrammes,
                      onChange: (val: string) => setEditedData(prev => ({ ...prev, programme: val }))
                    },
                    { label: "Graduation Year", key: "graduationYear", editable: true, readonly: false, type: "select", options: YEARS },
                    { label: "Designation", key: "designation", editable: true, readonly: false },
                    { label: "Location", key: "location", editable: true, readonly: false },
                    { label: "LinkedIn ID", key: "linkedinId", editable: true, readonly: false },
                    { 
                      label: "Date of Birth", 
                      key: "dob", 
                      format: formatDateForDisplay, 
                      editable: true, 
                      readonly: false,
                      type: "date"
                    },
                    { label: "Address", key: "address", editable: true, readonly: false },
                    { label: "Current Job", key: "currentPosition", editable: true, readonly: false },
                    { label: "Organisation", key: "organisation", editable: true, readonly: false },
                    { label: "Photo URL", key: "photoUrl", editable: true, readonly: false },
                    { label: "Area of Study", key: "areaOfStudy", editable: true, readonly: false },
                    { label: "University Name", key: "universityName", editable: true, readonly: false },
                    { label: "Area of Interest", key: "areaOfInterest", editable: true, readonly: false },
                    { label: "Skills (comma separated)", key: "skills", format: (skills: unknown) => Array.isArray(skills) ? skills.join(', ') : '', editable: true, readonly: false },
                    { label: "Registration No", key: "registrationNo", editable: false, readonly: true }
                  ];
                  return fields[i] ? (
                    <div key={fields[i].key}>
                      <label className="block text-sm font-medium mb-1">{fields[i].label}</label>
                      {fields[i].key === "dob" && fields[i].type === "date" && (props.userRole === "admin" || props.userRole === "alumni-manager" || props.userRole === "cadmin") ? (
                        <CustomDatePicker
                          value={editedData[fields[i].key] as string || ""}
                          onChange={(date) => setEditedData({ ...editedData, [fields[i].key]: date })}
                        />
                      ) : fields[i].type === "select" ? (
                        <select
                          value={editedData[fields[i].key] as string || ""}
                          onChange={fields[i].editable ? (e) => setEditedData({ ...editedData, [fields[i].key]: e.target.value }) : undefined}
                          disabled={fields[i].readonly}
                          className={`flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ${fields[i].readonly ? "bg-gray-100 cursor-not-allowed" : ""}`}
                        >
                          <option value="">Select {fields[i].label}</option>
                          {fields[i].options?.map((opt: string) => <option key={opt} value={opt}>{opt}</option>)}
                        </select>
                      ) : (
                        <Input
                          value={fields[i].format ? fields[i].format(editedData[fields[i].key]) : (editedData[fields[i].key] || '')}
                          onChange={fields[i].editable ? (e) => setEditedData({ ...editedData, [fields[i].key]: e.target.value }) : undefined}
                          readOnly={fields[i].readonly}
                          disabled={fields[i].readonly}
                          className={fields[i].readonly ? "bg-gray-100 cursor-not-allowed" : ""}
                        />
                      )}
                    </div>
                  ) : null;
                }))}
                  {/* School: only Graduation Year and Current Position editable, rest read-only */}
                  {props.userRole === "school" && ([...Array(20)].map((_, i) => {
                    const fields = [
                      { label: "Name", key: "name", editable: false, readonly: true, type: "text" },
                      { label: "Email", key: "email", editable: false, readonly: true, type: "email" },
                      { label: "Personal Email", key: "personalEmail", editable: false, readonly: true, type: "email" },
                      { label: "Phone", key: "phone", editable: false, readonly: true, type: "tel" },
                      { label: "School", key: "school", editable: false, readonly: true },
                      { label: "Programme", key: "programme", editable: false, readonly: true },
                      { label: "Graduation Year", key: "graduationYear", editable: true, readonly: false },
                      { label: "Designation", key: "designation", editable: false, readonly: true },
                      { label: "Location", key: "location", editable: false, readonly: true },
                      { label: "LinkedIn ID", key: "linkedinId", editable: false, readonly: true },
                      { label: "Date of Birth", key: "dob", format: formatDateForDisplay, editable: false, readonly: true },
                      { label: "Address", key: "address", editable: false, readonly: true },
                      { label: "Current Job", key: "currentPosition", editable: true, readonly: false },
                      { label: "Organisation", key: "organisation", editable: true, readonly: false },
                      { label: "Photo URL", key: "photoUrl", editable: false, readonly: true },
                      { label: "Department", key: "department", editable: false, readonly: true },
                      { label: "Area of Study", key: "areaOfStudy", editable: false, readonly: true },
                      { label: "University Name", key: "universityName", editable: false, readonly: true },
                      { label: "Area of Interest", key: "areaOfInterest", editable: false, readonly: true },
                      { label: "Skills (comma separated)", key: "skills", format: (skills: unknown) => Array.isArray(skills) ? skills.join(', ') : '', editable: false, readonly: true },
                      { label: "Registration No", key: "registrationNo", editable: false, readonly: true }
                    ];
                    return fields[i] ? (
                      <div key={fields[i].key}>
                        <label className="block text-sm font-medium mb-1">{fields[i].label}</label>
                        {(fields[i].key === 'name' || fields[i].key === 'email' || fields[i].key === 'phone') ? (
                          <div className="p-2 bg-gray-50 border rounded-md text-gray-600 min-h-[36px] flex items-center">
                            {typeof editedData[fields[i].key] === 'string' ? editedData[fields[i].key] : ''}
                          </div>
                        ) : (
                          <Input
                            value={fields[i].format ? fields[i].format(editedData[fields[i].key]) : (typeof editedData[fields[i].key] === 'string' ? editedData[fields[i].key] : '')}
                            onChange={fields[i].editable ? (e) => setEditedData({ ...editedData, [fields[i].key]: e.target.value }) : undefined}
                            readOnly={fields[i].readonly}
                            disabled={fields[i].readonly}
                            type={fields[i].type || 'text'}
                            className={`${fields[i].readonly ? "bg-gray-100 cursor-not-allowed" : ""} h-[36px]`}
                          />
                        )}
                      </div>
                    ) : null;
                  }))}
                  {/* Department: only Current Position editable, rest read-only */}
                  {props.userRole === "department" && ([...Array(20)].map((_, i) => {
                    const fields = [
                      { label: "Name", key: "name", editable: false, readonly: true, type: "text" },
                      { label: "Email", key: "email", editable: false, readonly: true, type: "email" },
                      { label: "Personal Email", key: "personalEmail", editable: false, readonly: true, type: "email" },
                      { label: "Phone", key: "phone", editable: false, readonly: true, type: "tel" },
                      { label: "School", key: "school", editable: false, readonly: true },
                      { label: "Programme", key: "programme", editable: false, readonly: true },
                      { label: "Graduation Year", key: "graduationYear", editable: false, readonly: true },
                      { label: "Designation", key: "designation", editable: false, readonly: true },
                      { label: "Location", key: "location", editable: false, readonly: true },
                      { label: "LinkedIn ID", key: "linkedinId", editable: false, readonly: true },
                      { label: "Date of Birth", key: "dob", format: formatDateForDisplay, editable: false, readonly: true },
                      { label: "Address", key: "address", editable: false, readonly: true },
                      { label: "Current Job", key: "currentPosition", editable: true, readonly: false },
                      { label: "Organisation", key: "organisation", editable: true, readonly: false },
                      { label: "Photo URL", key: "photoUrl", editable: false, readonly: true },
                      { label: "Department", key: "department", editable: false, readonly: true },
                      { label: "Area of Study", key: "areaOfStudy", editable: false, readonly: true },
                      { label: "University Name", key: "universityName", editable: false, readonly: true },
                      { label: "Area of Interest", key: "areaOfInterest", editable: false, readonly: true },
                      { label: "Skills (comma separated)", key: "skills", format: (skills: unknown) => Array.isArray(skills) ? skills.join(', ') : '', editable: false, readonly: true },
                      { label: "Registration No", key: "registrationNo", editable: false, readonly: true }
                    ];
                    return fields[i] ? (
                      <div key={fields[i].key}>
                        <label className="block text-sm font-medium mb-1">{fields[i].label}</label>
                        {(fields[i].key === 'name' || fields[i].key === 'email' || fields[i].key === 'phone') ? (
                          <div className="p-2 bg-gray-50 border rounded-md text-gray-600 min-h-[36px] flex items-center">
                            {typeof editedData[fields[i].key] === 'string' ? editedData[fields[i].key] : ''}
                          </div>
                        ) : (
                          <Input
                            value={fields[i].format ? fields[i].format(editedData[fields[i].key]) : (typeof editedData[fields[i].key] === 'string' ? editedData[fields[i].key] : '')}
                            onChange={fields[i].editable ? (e) => setEditedData({ ...editedData, [fields[i].key]: e.target.value }) : undefined}
                            readOnly={fields[i].readonly}
                            disabled={fields[i].readonly}
                            type={fields[i].type || 'text'}
                            className={`${fields[i].readonly ? "bg-gray-100 cursor-not-allowed" : ""} h-[36px]`}
                          />
                        )}
                      </div>
                    ) : null;
                  }))}
                <div className="md:col-span-2 lg:col-span-3">
                  <label className="block text-sm font-medium mb-1">Feedback</label>
                  <Input
                    value={editedData.feedback || ''}
                    readOnly
                    disabled
                    className="bg-gray-100 cursor-not-allowed"
                  />
                </div>
              </div>
              <div className="flex justify-end gap-2 mt-6">
                <Button variant="outline" onClick={handleCancelEdit} disabled={saving}>Cancel</Button>
                <Button onClick={handleSaveStudent} disabled={saving}>
                  {saving ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : <Save className="h-4 w-4 mr-1" />}
                  {saving ? "Saving..." : "Save"}
                </Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </CardContent>
    </Card>
  );
};



export default AlumniManagementTab;